on: [push]
jobs:
  build:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
    - name: trigger job test
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.sdpmlab.org/"
        user: "ashleyjuan"
        token: "${{secrets.TOKEN}}"
        job: "410977002"
